In [225]:
import pandas as pd
import numpy as np
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import warnings
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
from sklearn.decomposition import PCA
from sklearn.exceptions import DataConversionWarning
from sklearn.metrics.pairwise import cosine_similarity 
warnings.filterwarnings(action='ignore')
ds = pd.read_csv('data.csv')

In [226]:
fifa = pd.read_csv('data.csv')

In [227]:
fifa.shape

(18207, 89)

In [228]:
fifa.head(10)

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,5,183277,E. Hazard,27,https://cdn.sofifa.org/players/4/19/183277.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,91,Chelsea,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
6,6,177003,L. Modrić,32,https://cdn.sofifa.org/players/4/19/177003.png,Croatia,https://cdn.sofifa.org/flags/10.png,91,91,Real Madrid,...,84.0,60.0,76.0,73.0,13.0,9.0,7.0,14.0,9.0,€137.4M
7,7,176580,L. Suárez,31,https://cdn.sofifa.org/players/4/19/176580.png,Uruguay,https://cdn.sofifa.org/flags/60.png,91,91,FC Barcelona,...,85.0,62.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0,€164M
8,8,155862,Sergio Ramos,32,https://cdn.sofifa.org/players/4/19/155862.png,Spain,https://cdn.sofifa.org/flags/45.png,91,91,Real Madrid,...,82.0,87.0,92.0,91.0,11.0,8.0,9.0,7.0,11.0,€104.6M
9,9,200389,J. Oblak,25,https://cdn.sofifa.org/players/4/19/200389.png,Slovenia,https://cdn.sofifa.org/flags/44.png,90,93,Atlético Madrid,...,70.0,27.0,12.0,18.0,86.0,92.0,78.0,88.0,89.0,€144.5M

In [229]:
# If right foot then 1 else 0

fifa['Preferred Foot'] = np.where(fifa['Preferred Foot'] == "Right",1,0)

In [233]:
# remove the currency symbol and letters M and K
# if value is in thousands, then divide to render all the values in terms of millions

def fixMoney(x):
    try:
        x = x.replace('€','')
        lastChar = len(x)-1
        thousand = False
        if x[lastChar] == 'K':
            thousand = True
            x = x.replace('K','')
        elif x[lastChar] == 'M':
            thousand = False
            x = x.replace('M','')
        x = float(x)
        if thousand:
            x = x/1000
    except:
        x = 0
    return x


fifa['Value'] = fifa['Value'].apply(fixMoney)

In [234]:
fixMoney(fifa.loc[18206,'Value'])

0

In [235]:
fifa['Value']

0        110.50
1         77.00
2        118.50
3         72.00
4        102.00
5         93.00
6         67.00
7         80.00
8         51.00
9         68.00
10        77.00
11        76.50
12        44.00
13        60.00
14        63.00
15        89.00
16        83.50
17        78.00
18        58.00
19        53.50
20        51.50
21        60.00
22        38.00
23        64.50
24        27.00
25        81.00
26        69.50
27        59.50
28        69.50
29        62.00
          ...
18177      0.07
18178      0.05
18179      0.05
18180      0.04
18181      0.05
18182      0.05
18183      0.00
18184      0.04
18185      0.05
18186      0.06
18187      0.04
18188      0.06
18189      0.06
18190      0.06
18191      0.05
18192      0.05
18193      0.05
18194      0.05
18195      0.06
18196      0.06
18197      0.06
18198      0.06
18199      0.07
18200      0.06
18201      0.06
18202      0.06
18203      0.06
18204      0.06
18205      0.06
18206      0.06
Name: Value, Length: 18207, dtype: float64

In [236]:
fifa.to_csv("fifa_1.csv")

In [237]:
fifa.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [238]:
# remove the currency symbol and letters K
# if value is in thousands, then divide to render all the values in terms of millions

def fixWage(x):
    try:
        x = x.replace('€','')
        lastChar = len(x)-1
        thousand = False
        x = x.replace('K','')
    except:
        x = 0
    return x


fifa['Wage'] = fifa['Wage'].apply(fixWage)

In [239]:
fifa['Wage']

0        565
1        405
2        290
3        260
4        355
5        340
6        420
7        455
8        380
9         94
10       205
11       355
12       125
13       285
14       225
15       205
16       205
17       145
18       240
19       240
20       315
21       200
22       130
23       300
24       215
25       100
26       255
27       285
28       315
29       165
        ...
18177      1
18178      1
18179      1
18180      1
18181      1
18182      1
18183      1
18184      1
18185      1
18186      1
18187      1
18188      1
18189      1
18190      1
18191      1
18192      1
18193      1
18194      1
18195      1
18196      1
18197      1
18198      1
18199      1
18200      1
18201      1
18202      1
18203      1
18204      1
18205      1
18206      1
Name: Wage, Length: 18207, dtype: object

In [240]:
fifa.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [241]:
fifa.to_csv('fifa_2.csv')

In [247]:
fifa['Value']

0        110.50
1         77.00
2        118.50
3         72.00
4        102.00
5         93.00
6         67.00
7         80.00
8         51.00
9         68.00
10        77.00
11        76.50
12        44.00
13        60.00
14        63.00
15        89.00
16        83.50
17        78.00
18        58.00
19        53.50
20        51.50
21        60.00
22        38.00
23        64.50
24        27.00
25        81.00
26        69.50
27        59.50
28        69.50
29        62.00
          ...
18177      0.07
18178      0.05
18179      0.05
18180      0.04
18181      0.05
18182      0.05
18183      0.00
18184      0.04
18185      0.05
18186      0.06
18187      0.04
18188      0.06
18189      0.06
18190      0.06
18191      0.05
18192      0.05
18193      0.05
18194      0.05
18195      0.06
18196      0.06
18197      0.06
18198      0.06
18199      0.07
18200      0.06
18201      0.06
18202      0.06
18203      0.06
18204      0.06
18205      0.06
18206      0.06
Name: Value, Length: 18207, dtype: float64

In [248]:
fifa_clean = pd.read_csv('clean_fifa_1.csv')

In [244]:
fifa_clean['Wage'] = fifa_clean['Wage'].apply(fixWage)

In [250]:
fifa_clean = fifa_clean.drop(['Unnamed: 0','Unnamed: 0.1','Unnamed: 0.1.1','ID','Photo','Nationality','Flag',
                 'Club Logo', 'Special', 'Real Face', 'Jersey Number', 'Joined', 
                 'Loaned From', 'Contract Valid Until'],axis=1).copy()

In [251]:
def fixHeight(x):
    try:
        x_ht = x.replace('\'','-').split('-') 
        ft =int(x_ht[0])
        inches = int(x_ht[1])
        totalInches = (ft * 12) + inches
    except:
        totalInches = 0
    return totalInches

fifa_clean['Height'] = fifa_clean['Height'].apply(fixHeight)

In [252]:
def fixWeight(x):
    try:
        x = int(x.replace('lbs',''))        
    except:
        x = 0
    return x

fifa_clean['Weight'] = fifa_clean['Weight'].apply(fixWeight)

In [253]:
fifa_clean.to_csv('new_clean.csv')

In [254]:
fifa_clean1 = pd.read_csv('new_clean.csv')

In [255]:
fifa_clean1.isnull().sum()

Unnamed: 0                     0
Name                           0
Age                            0
Overall                        0
Potential                      0
Club                         241
Value                          0
Wage                           0
Preferred Foot                 0
International Reputation      48
Weak Foot                     48
Skill Moves                   48
Work Rate                     48
Body Type                     48
Position                      60
Height                         0
Weight                         0
LS                             0
ST                             0
RS                             0
LW                             0
LF                             0
CF                             0
RF                             0
RW                             0
LAM                            0
CAM                            0
RAM                            0
LM                             0
LCM                            0
                            ...
Dribbling                     48
Curve                         48
FKAccuracy                    48
LongPassing                   48
BallControl                   48
Acceleration                  48
SprintSpeed                   48
Agility                       48
Reactions                     48
Balance                       48
ShotPower                     48
Jumping                       48
Stamina                       48
Strength                      48
LongShots                     48
Aggression                    48
Interceptions                 48
Positioning                   48
Vision                        48
Penalties                     48
Composure                     48
Marking                       48
StandingTackle                48
SlidingTackle                 48
GKDiving                      48
GKHandling                    48
GKKicking                     48
GKPositioning                 48
GKReflexes                    48
Release Clause              1564
Length: 78, dtype: int64

In [256]:
# fifa clean 2 has no names of player or clubs
fifa_clean2 = fifa_clean1.copy()
fifa_clean2 = fifa_clean2.drop(['Name','Club'],axis=1)

In [282]:
bodyType = fifa_clean2['Body Type'].str.get_dummies()
bodyType

       0  Lean  Normal  Stocky
0      0     0       1       0
1      0     1       0       0
2      0     1       0       0
3      0     1       0       0
4      0     0       1       0
5      0     0       1       0
6      0     1       0       0
7      0     0       1       0
8      0     0       1       0
9      0     0       1       0
10     0     0       1       0
11     0     0       1       0
12     0     1       0       0
13     0     0       1       0
14     0     1       0       0
15     0     0       1       0
16     0     0       1       0
17     0     1       0       0
18     0     0       1       0
19     0     1       0       0
20     0     1       0       0
21     0     1       0       0
22     0     0       1       0
23     0     0       0       1
24     0     0       1       0
25     0     1       0       0
26     0     0       1       0
27     0     0       1       0
28     0     0       1       0
29     0     0       1       0
...   ..   ...     ...     ...
18177  0     1       0       0
18178  0     1       0       0
18179  0     1       0       0
18180  0     1       0       0
18181  0     1       0       0
18182  0     1       0       0
18183  0     0       1       0
18184  0     0       1       0
18185  0     0       1       0
18186  0     0       1       0
18187  0     1       0       0
18188  0     1       0       0
18189  0     1       0       0
18190  0     0       1       0
18191  0     1       0       0
18192  0     1       0       0
18193  0     1       0       0
18194  0     0       1       0
18195  0     0       1       0
18196  0     1       0       0
18197  0     0       1       0
18198  0     1       0       0
18199  0     1       0       0
18200  0     1       0       0
18201  0     1       0       0
18202  0     1       0       0
18203  0     0       1       0
18204  0     0       1       0
18205  0     1       0       0
18206  0     1       0       0

[18207 rows x 4 columns]

In [283]:
def appendToPosition(x):
    x = str(x) + "-Position"
    return x

fifa_clean2['Position'] = fifa_clean2['Position'].apply(appendToPosition)

In [284]:
position = fifa_clean2['Position'].str.get_dummies()
position

,CAM-Position-Position,CB-Position-Position,CDM-Position-Position,CF-Position-Position,CM-Position-Position,GK-Position-Position,LAM-Position-Position,LB-Position-Position,LCB-Position-Position,LCM-Position-Position,...,RCB-Position-Position,RCM-Position-Position,RDM-Position-Position,RF-Position-Position,RM-Position-Position,RS-Position-Position,RW-Position-Position,RWB-Position-Position,ST-Position-Position,nan-Position-Position
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
11,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
12,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
17,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
24,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
27,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18177,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18178,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18179,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18180,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18181,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18182,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18183,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18184,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18185,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
18186,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18187,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18188,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18189,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18190,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18191,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
18192,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18193,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18194,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18195,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18196,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18197,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18198,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18199,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18200,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18201,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18202,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18203,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18204,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18205,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
18206,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [285]:
fifa_clean2 = pd.concat([fifa_clean2, bodyType, position], axis=1)

In [287]:
# fifa_clean2 = fifa_clean2.drop(['nan-Position'],axis=1)

In [289]:
fifa_clean2 = fifa_clean2.drop(['Body Type','Position'],axis=1)

In [296]:
fifa_clean2.to_csv('fifa_clean_final.csv')

In [298]:
fifa_clean_3 = pd.read_csv('fifa_clean_final.csv')
fifa_clean_3.head()

,Unnamed: 0,Age,Overall,Potential,Value,Wage,Preferred Foot,International Reputation,Weak Foot,Skill Moves,...,RCB-Position-Position,RCM-Position-Position,RDM-Position-Position,RF-Position-Position,RM-Position-Position,RS-Position-Position,RW-Position-Position,RWB-Position-Position,ST-Position-Position,nan-Position-Position
0,0,31,94,94,110.5,0.565,0,5,4,4,...,0,0,0,1,0,0,0,0,0,0
1,1,33,94,94,77.0,0.405,1,5,4,5,...,0,0,0,0,0,0,0,0,1,0
2,2,26,92,93,118.5,0.290,1,5,5,5,...,0,0,0,0,0,0,0,0,0,0
3,3,27,91,93,72.0,0.260,1,4,3,1,...,0,0,0,0,0,0,0,0,0,0
4,4,27,91,92,102.0,0.355,1,4,5,4,...,0,1,0,0,0,0,0,0,0,0

In [263]:
fifa_clean2['Release Clause'] = fifa_clean2['Release Clause'].apply(fixMoney)

fifa_clean2['Wage'] = fifa_clean2['Wage'].apply(fixMoney)

fifa_clean2.to_csv("fifa_clean2.csv")

fifa_clean2 = fifa_clean2.fillna(value=0)

In [362]:
### Cosine similarity

def recommend_cosine(player):
    index = get_index(player)
    similarities = cosine_similarity(fifa_clean_3)
    playerIndex = similarities[index,:].argsort()[-16:][::-1][1:]
    for i in playerIndex:
        print(fifa_clean1.loc[i,'Name'])

In [427]:
## Pjanic for P. Pogba ------ GOOD
## Salah for L. Suárez and Coutinho ------ GOOD
## Courtois for K. Navas
## W. Szczęsny for Alisson and vice versa
## S. Mane for R. Sterling
## Coutinho for Neymar Jr
## Lacazatte for A. Sánchez
## Gnabry for A. Robben
## A. Sánchez for I. Perišić
## A. Laporte for V. Kompany
## S. Lichtsteiner for F. Coquelin

recommend_cosine('L. Martínez')

D. Benedetto
Richarlison
L. Alario
A. Rebić
M. Gómez
Zé Luís
Roger
André Silva
B. Verbič
K. Toko-Ekambi
S. Bergwijn
A. Sanabria
Fernando Torres
Luimo Boas Santos
Alexandre Pato

In [365]:
# recommendations = NearestNeighbors(n_neighbors=11, algorithm='ball_tree').fit(fifa_clean2)

In [428]:
player_indices = recommendations.kneighbors(fifa_clean2)[1]

def get_index(x):
    return fifa_clean1[fifa_clean1['Name']==x].index.tolist()[0]

def recommend_me(player):
    print('Here are 10 players similar to', player, ':' '\n')
    index = get_index(player)
    for i in player_indices[index][1:]:
            print(fifa_clean1.iloc[i]['Name'], '\n')

In [429]:
len(fifa_clean1)

18207

In [499]:
fifa_xi['Position'].dropna(inplace=True)

In [500]:
def replacePositions(x):
    if x == 'RF' or x == 'LF' or x == 'ST' or x == 'LS' or x == 'RS' or x == 'LW' or x == 'RW':
        x = x.replace(x,'F')
    elif x == 'RCM' or x == 'LCM' or x == 'LDM' or x == 'RDM' or x == 'CAM' or x == 'CDM' or x == 'CM' or x == 'RAM' or x == 'LAM' or x == 'LM' or x == 'RM':
        x = x.replace(x,'M')
    elif x == 'RCB' or x == 'CB' or x == 'LCB' or x == 'LB' or x == 'RB' or x == 'RWB' or x == 'RWB':
        x = x.replace(x,'D')
    else:
        x = x.replace(x,'G')
    return x

fifa_xi['Position'] = fifa_xi['Position'].apply(replacePositions)

In [503]:
fifa_xi.head(10)

                Name  Overall Position  Value   Wage
0           L. Messi       94        F  110.5  0.565
1  Cristiano Ronaldo       94        F   77.0  0.405
2          Neymar Jr       92        F  118.5  0.290
3             De Gea       91        G   72.0  0.260
4       K. De Bruyne       91        M  102.0  0.355
5          E. Hazard       91        F   93.0  0.340
6          L. Modrić       91        M   67.0  0.420
7          L. Suárez       91        F   80.0  0.455
8       Sergio Ramos       91        D   51.0  0.380
9           J. Oblak       90        G   68.0  0.094

In [465]:
fifa_xi = fifa_clean1[['Name', 'Overall', 'Position', 'Value', 'Wage']].copy()

In [466]:
fifa_xi['Wage'] = fifa_xi['Wage'].apply(fixMoney)

In [510]:
len(fifa_clean1[0:100])

100

In [574]:
## minimize the budget
## maximize the overall rating

def bestEleven(budget):
    team = []
    players = 0
    defenders = 0
    midfielders = 0
    forwards = 0
    emptyNet = True
    
    defendersCost = 0
    midfieldersCost = 0
    forwardsCost = 0
    
    teamCost = 0
    teamRating = 0
    
    for i in range(len(fifa_clean1[0:1000])):
        
        forwardsBudget = budget/3
        midfieldersBudget = budget/3
        defendersBudget = budget/4
        keeperBudget = budget - (forwardsBudget + midfieldersBudget + defendersBudget)
           
        ## calculate total cost of player
        value = fifa_xi.loc[i, 'Value']
        wage = fifa_xi.loc[i, 'Wage']

        playerCost = value + 52*wage
        teamCost += playerCost
        
        # position
        playerPos = fifa_xi.loc[i, 'Position']
        
        if players <= 11:
            if playerPos == 'D' and defenders <= 4:
                defendersCost += playerCost
                if defendersCost <= defendersBudget: 
                    team.append(fifa_xi.loc[i,'Name'])
                    players += 1
                    defenders += 1
                    defendersBudget -= playerCost
            elif playerPos == 'M' and midfielders <= 3:
                midfieldersCost += playerCost
                if midfieldersCost <= midfieldersBudget: 
                    team.append(fifa_xi.loc[i,'Name'])
                    players += 1
                    midfielders += 1
            elif playerPos == 'F' and forwards <= 3:
                forwardsCost += playerCost
                if forwardsCost <= forwardsBudget: 
                    team.append(fifa_xi.loc[i,'Name'])
                    players += 1
                    forwards += 1
            else: ## keeper
                if playerCost <= keeperBudget and emptyNet:
                    team.append(fifa_xi.loc[i,'Name'])
                    players += 1
                    emptyNet = False
    
    print(team)

In [579]:
bestEleven(500)

['L. Messi', 'K. De Bruyne', 'Sergio Ramos', 'D. Godín', 'S. Handanovič']

In [577]:
fifa_xi.to_csv('fifa_xi.csv')

In [629]:
df=pd.read_csv("fifa_clean_final.csv")

In [630]:
goalkeeper=np.array([])
cendefenders=np.array([])
fbacks=np.array([])
midfielders=np.array([])
forwards=np.array([])
for i in df.index:
    if(df.loc[i,"GK-Position-Position"]==1):
        goalkeeper=np.append(goalkeeper,i)
    if(df.loc[i,"CB-Position-Position"]==1 or df.loc[i,"LCB-Position-Position"]==1 or df.loc[i,"RCB-Position-Position"]==1):
        cendefenders=np.append(cendefenders,i)
    if(df.loc[i,"LB-Position-Position"]==1 or df.loc[i,"LWB-Position-Position"]==1 or df.loc[i,"RWB-Position-Position"]==1 or df.loc[i,"RB-Position-Position"]==1):
        fbacks=np.append(fbacks,i)
    if(df.loc[i,"CAM-Position-Position"]==1 or df.loc[i,"CDM-Position-Position"]==1 or df.loc[i,"CM-Position-Position"]==1 or df.loc[i,"LAM-Position-Position"]==1 or df.loc[i,"LCM-Position-Position"]==1 or df.loc[i,"LDM-Position-Position"]==1 or df.loc[i,"LM-Position-Position"]==1 or df.loc[i,"RCM-Position-Position"]==1 or df.loc[i,"RAM-Position-Position"]==1 or df.loc[i,"RDM-Position-Position"]==1 or df.loc[i,"RM-Position-Position"]==1):
        midfielders=np.append(midfielders,i)
    if(df.loc[i,"LS-Position-Position"]==1 or df.loc[i,"RS-Position-Position"]==1 or df.loc[i,"ST-Position-Position"]==1 or df.loc[i,"RW-Position-Position"]==1 or df.loc[i,"LW-Position-Position"]==1or df.loc[i,"RW-Position-Position"]==1 or df.loc[i,"RF-Position-Position"]==1 or df.loc[i,"LF-Position-Position"]==1 or df.loc[i,"CF-Position-Position"]==1):
        forwards=np.append(forwards,i)

In [659]:
print(goalkeeper[0]," ",cendefenders[0:2]," ",fbacks[0:2]," ",midfielders[0:4]," ",forwards[0:2])

3.0   [ 8. 12.]   [35. 49.]   [ 4.  6. 11. 13.]   [0. 1.]

In [688]:
def bestEleven(budget):
    for i in range(2025):
        summ=df.loc[goalkeeper[i],'Fee']+df.loc[cendefenders[i],'Fee']+ \
        df.loc[cendefenders[i+1],'Fee']+df.loc[fbacks[i],'Fee']+ \
        df.loc[fbacks[i+1],'Fee']+df.loc[midfielders[i],'Value']+ \
        df.loc[midfielders[i+1],'Fee']+df.loc[midfielders[i+2],'Fee']+ \
        df.loc[midfielders[i+3],'Fee']+df.loc[forwards[i],'Fee']+ \
        df.loc[forwards[i+1],'Fee']
        if(summ<=budget):
            print("Your ")
            print("The best playing eleven with a total cost of", summ, " million euros:")
            print("GoalKeeper: ", get_player(goalkeeper[i]), 
                  "\nCenter backs: ", get_player(cendefenders[i]), " ", get_player(cendefenders[i+1]), 
                  "\nFullbacks: ", get_player(fbacks[i])," ",  get_player(fbacks[i+1])," ",
                  "\nMidfielders: " , get_player(midfielders[i])," ", get_player(midfielders[i+1])," ", get_player(midfielders[i+2])," ", get_player(midfielders[i+3]),
                  "\nForwards: ", get_player(forwards[i])," ", get_player(forwards[i+1]))
            break

In [689]:
bestEleven(1000)

The best playing eleven with a total cost of 914.1600000000001  million euros:
GoalKeeper:  De Gea
Center backs:  Sergio Ramos   D. Godín
Fullbacks:  Marcelo   Jordi Alba
Midfielders:  K. De Bruyne   L. Modrić   T. Kroos   David Silva
Forwards:  L. Messi   Cristiano Ronaldo

In [652]:
def get_index(x):
    return fifa_clean1[fifa_clean1['Name']==x].index.tolist()[0]

In [626]:
def get_player(ind):
    return fifa_clean1.loc[ind,'Name']

In [627]:
get_player(147)

'S. Ruffier'